version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: sh -c "python manage.py makemigrations core && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    environment:
      - VITE_API_BASE=http://localhost:8000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
